In [19]:
arr=[1,2,3,4,5,6,7,8,9,10]
print(arr[:5:-2])

[10, 8]


In [20]:
data = list(range(10))
print(data[::-1])

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [21]:
#Получите массив без первого и двух последних элементов:
data = list(range(10))
print(data[1:8:1])

[1, 2, 3, 4, 5, 6, 7]


In [22]:
 import numpy as np

In [23]:
arr_1d = np.array([1, 2, 3])

In [24]:
print(arr_1d)
print(type(arr_1d))
print(arr_1d.shape)
print(arr_1d[0])
print(arr_1d[2])
print(arr_1d[-1])

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1
3
3


In [25]:
data = np.random.randint(low=0, high=10, size=(5, 6))
print(data)

[[7 9 7 0 8 5]
 [2 4 9 7 4 5]
 [9 3 3 7 1 2]
 [1 1 9 8 7 5]
 [3 5 2 8 0 5]]


In [26]:
data = np.random.randint(low=0, high=10, size=(3, 6))
print(data)

[[3 3 9 4 8 5]
 [5 0 1 6 3 3]
 [2 3 1 7 5 7]]


In [30]:
data = np.random.randint(low=0, high=10, size=(3, 6))
print(data)
a=np.random.permutation(data)
print(a)

[[9 2 3 4 0 8]
 [6 9 7 0 8 4]
 [7 0 1 0 1 4]]
[[7 0 1 0 1 4]
 [9 2 3 4 0 8]
 [6 9 7 0 8 4]]


In [46]:
#Определите, имеется ли хотя бы одно значение больше пяти и меньше восьми в массиве:
#
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print((arr>5)&(arr<8))


[[False False False False]
 [False  True  True False]
 [False False False False]]


# Больше индексации

In [47]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [49]:
# Получим маску и воспользуемся ею для индексации
mask = arr > 6
print(mask)
print(arr[mask])

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[ 7  8  9 10 11 12]


In [50]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print(arr.flatten())

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [51]:
data = np.random.randint(low=0, high=5, size=(3, 6))
print(np.sum(data))

34


In [54]:
x = np.arange(10).reshape((2, 5))
y = np.arange(15).reshape((3, 5))

print(x)
print(y)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [55]:
print(np.concatenate((x, y), axis=0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# Задание
Объедините три массива вдоль колонок:# 

In [53]:
x = np.arange(9).reshape((3, 3))
y = np.arange(12).reshape((3, 4))
z = np.arange(15).reshape((3, 5))

print(np.concatenate((x, y,z), axis=1))

# TODO - получите объединенный массив:
# [[ 0  1  2  0  1  2  3  0  1  2  3  4]
#  [ 3  4  5  4  5  6  7  5  6  7  8  9]
#  [ 6  7  8  8  9 10 11 10 11 12 13 14]]

[[ 0  1  2  0  1  2  3  0  1  2  3  4]
 [ 3  4  5  4  5  6  7  5  6  7  8  9]
 [ 6  7  8  8  9 10 11 10 11 12 13 14]]


In [56]:
#Напишите реализацию добавления стобца единиц к матрице слева:
#Напишите реализацию добавления стобца единиц к матрице слева:#
x = np.arange(1, 10).reshape((3, 3))
new_x = np.ones((3, 1))
b = np.hstack([new_x, x])
print(b)
# TODO - получить матрицу со столбцом единиц слева
# [[1 1 2 3]
#  [1 4 5 6]
#  [1 7 8 9]]

[[1. 1. 2. 3.]
 [1. 4. 5. 6.]
 [1. 7. 8. 9.]]


По такому же принципу именования найдите функцию, которая возвращает индекс максимального/минимального (в завимости от варианта) элемента в массиве.

Воспользуйтесь найденной функцией и найдите индексы максимальных элементов в каждом столбце 2D матрицы:# 

In [57]:
arr = np.array([
    [11, -1, 1, 3, 5],
    [6, 1, 0, -1, 10],
    [1, 3, 2, 3, 6],
    [5, 2, 7, 8, 9],
])
print(np.argmax(arr, axis=0)) 
print(np.argmin(arr, axis=0)) 
#   TODO   [0 2 3 3 1]/[2 0 1 1 0]#


[0 2 3 3 1]
[2 0 1 1 0]


In [84]:
#Напишите код сортировки массива по столбцам:
import numpy as np
arr = np.array([
    [11, 2, 1, 3, 5],
    [6, 2, 0, -1, 10],
    [1, 3, 2, 3, 5],
    [5, 2, 7, 8, 9],
])
print(arr)
new_arr=np.sort(arr,axis=0)
print(new_arr)

[[11  2  1  3  5]
 [ 6  2  0 -1 10]
 [ 1  3  2  3  5]
 [ 5  2  7  8  9]]
[[ 1  2  0 -1  5]
 [ 5  2  1  3  5]
 [ 6  2  2  3  9]
 [11  3  7  8 10]]


In [83]:
#Создайте массив, состоящий из случайных элементов в диапазоне $[-10; 20]$ размером $(5, 7)$:

np.random.randint(-10, 10, size=(5, 7))


array([[ -6,   7,   8,  -2, -10,   4,   1],
       [  0,   8,  -6,  -7,  -8,  -5,  -5],
       [ -4,  -3,   1,  -7,  -7,   4,  -3],
       [ -9,   9,  -7,  -8,  -5,   4,  -7],
       [  1,  -5,  -8,  -9,   5,  -9, -10]])

In [87]:
data = np.arange(1, 16).reshape((3, 5))
data = np.pad(data, pad_width=1, mode='constant', constant_values=0)
print(data)

[[ 0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  0]
 [ 0  6  7  8  9 10  0]
 [ 0 11 12 13 14 15  0]
 [ 0  0  0  0  0  0  0]]


In [88]:
#Разберитесь с функцией np.clip() 
#и произведите ограничение массива, 
#чтобы в нем значения были не более шести 
#и не менее двух:
data = np.arange(1, 16).reshape((3, 5))
data = np.clip(data, 2, 6)
print(data)
# TODO - ограничьте значения массива
# [[2 2 3 4 5]
#  [6 6 6 6 6]
#  [6 6 6 6 6]]

[[2 2 3 4 5]
 [6 6 6 6 6]
 [6 6 6 6 6]]


In [107]:
data = np.full((3, 5), fill_value=2, dtype=np.int32)

data1=np.arange(data.shape[1])
data2=data**data1
print(data2)

[[ 1  2  4  8 16]
 [ 1  2  4  8 16]
 [ 1  2  4  8 16]]


In [108]:
#Умножьте каждую колонку на ее индекс:
data = np.full((3, 5), fill_value=2, dtype=np.int32)
print(data)
data1=np.arange(data.shape[1])
data2=data*data1
print(data2)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
[[0 2 4 6 8]
 [0 2 4 6 8]
 [0 2 4 6 8]]


In [93]:
#Умножьте каждый четный ряд в матрице на вектор:
import numpy as np
data = np.repeat(np.arange(1, 8), 4).reshape(7, 4)
vec = np.array([1, 2, 1, 2])
print(data)
print()
for i in range(data.shape[0]):
    if i%2==0:
      data[i,:]=data[i,:]*vec
print (data)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]

[[ 1  2  1  2]
 [ 2  2  2  2]
 [ 3  6  3  6]
 [ 4  4  4  4]
 [ 5 10  5 10]
 [ 6  6  6  6]
 [ 7 14  7 14]]


In [94]:
#Определите индексы двух наибольших элементов в матрице по каждому ряду:
data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 4, 24, 24, 28,  3, 40]])
idx = (-data).argsort()[:4]
print(idx[:,[0,1]])
# TODO - определите индексы двух наибольших элементов по каждому ряду
# [[4 1]
#  [1 2]
#  [3 1]
#  [5 3]]

[[4 1]
 [1 2]
 [3 1]
 [5 3]]


In [96]:
#Выберите две случайные колонки из массива:
data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 4, 24, 24, 28,  3, 40]])

# TODO - выберите случайные две колонки из массива
# *Например,
# [[22  8]
#  [25 15]
#  [16  9]
#  [24 40]]

In [99]:
#Создайте массив размером $(10, 3)$, который состоит из повторяющихся рядов исходного массива:
data = np.arange(9).reshape(3, 3)
data = np.tile(data,(3,1))
print(data)
# TODO - создайте массив из повторяющихся рядов размером (10, 3)

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]]


In [98]:
#Соберите массив, состоящий из элементов 2й и 4й колонок и строк с 1й по 3ю
data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 14, 9,  33, 21,  7,  6],
                [ 4, 24, 24, 28,  3, 40]])
print([data[1,2],data[1,4]])
print([data[2,2],data[2,4]])
print([data[3,2],data[3,4]])


# TODO - соберите матрицу из конкретных элементов массива
# [[23 22]
#  [ 9  0]
#  [33  7]]

[23, 22]
[9, 0]
[33, 7]


In [97]:
#Инвертируйте порядок элементов в последних двух колонках:
import numpy as np
data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 14, 9,  33, 21,  7,  6],
                [ 4, 24, 24, 28,  3, 40]])
b = data[:, [-2, -1]]
you = np.flipud(b)
zuo = np.delete(data, [4,5], axis=1)
print(np.hstack((zuo,you)))


# TODO - инвертируйте порядок последних двух колонок
# [[20 22  2 14  3 40]
#  [ 7 25 23  3  7  6]
#  [ 8 16  9 22  0  9]
#  [14  9 33 21 22 15]
#  [ 4 24 24 28 25  8]]

[[20 22  2 14  3 40]
 [ 7 25 23  3  7  6]
 [ 8 16  9 22  0  9]
 [14  9 33 21 22 15]
 [ 4 24 24 28 25  8]]
