In [1]:
pip install pandas==1.0.0


  Attempting uninstall: pandas
    Found existing installation: pandas 1.1.3
    Uninstalling pandas-1.1.3:
      Successfully uninstalled pandas-1.1.3


In [2]:
import pandas as pd


In [5]:
import numpy as np
arr = np.random.randint(0, 10, size=(5, 3))
print(arr)

[[2 4 8]
 [8 4 6]
 [8 2 4]
 [7 9 4]
 [8 6 3]]


In [7]:
arr = np.random.randint(0, 10, size=(5, 3))
print(arr)
df = pd.DataFrame(
    data=arr,
    columns=['x1', 'x2', 'x3'],
    index=['A','B','C','D','E']
)
df


[[7 2 7]
 [2 0 2]
 [2 4 9]
 [0 9 6]
 [3 7 0]]


x1  x2  x3
A   7   2   7
B   2   0   2
C   2   4   9
D   0   9   6
E   3   7   0

In [8]:
# Создается словарь, в котором ключи будут названиями колонок,
#   а значения - данные по этим колонкам
data = {
    'test_1_mark': [4.6, 3.8, 5.0, 4.5],
    'test_2_mark': [5.0, 3.9, 4.7, 4.5]
}

pd.DataFrame(data)

test_1_mark  test_2_mark
0          4.6          5.0
1          3.8          3.9
2          5.0          4.7
3          4.5          4.5

In [9]:
# Создается список записей, каждая запись представлена словарем
# В словаре ключи - названия колонок
# При создании фрейма pandas просмотри все возможные ключи словарей в списке
#   и создаст колонок по их названиям
data = [
    {
        'test_1_mark': 4.6,
        'test_2_mark': 5.0
    },
    {
        'test_1_mark': 3.8,
        'test_2_mark': 3.9
    },
    {
        'test_1_mark': 5.0
    },
]

pd.DataFrame(data)

test_1_mark  test_2_mark
0          4.6          5.0
1          3.8          3.9
2          5.0          NaN

In [13]:
f = pd.DataFrame({'A': 1.,
                   'B': pd.Timestamp('20130102'),
                   'C': np.array([2.] * 4, dtype='float32'),
                   'D': np.array([3] * 4, dtype='int32'),
                   'E': pd.Categorical(["test", "train", "test", "train"]),
                   'F': 'foo'})
df


x1  x2  x3
0    0  -7   6
1   -4  -4  -7
2   -8  -9   2
3   -6   0   1
4   -9  -5  -8
5   -8   9  -1
6   -5  -6 -10
7    5   8   7
8    6  -5  -3
9    1  -9  -5
10   5   9  -9
11   4  -8  -7
12   4  -5   2
13   0   6  -3
14   2  -1   9

In [11]:
df = pd.DataFrame(
    data=np.random.randint(-10, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(4)

x1  x2  x3
0   0  -7   6
1  -4  -4  -7
2  -8  -9   2
3  -6   0   1

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x1      15 non-null     int32
 1   x2      15 non-null     int32
 2   x3      15 non-null     int32
dtypes: int32(3)
memory usage: 308.0 bytes


In [14]:
df.tail(4)

x1  x2  x3
11   4  -8  -7
12   4  -5   2
13   0   6  -3
14   2  -1   9

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x1      15 non-null     int32
 1   x2      15 non-null     int32
 2   x3      15 non-null     int32
dtypes: int32(3)
memory usage: 308.0 bytes


In [16]:
df.describe()

x1         x2         x3
count  15.000000  15.000000  15.000000
mean   -0.866667  -1.800000  -1.733333
std     5.330059   6.635403   6.076496
min    -9.000000  -9.000000 -10.000000
25%    -5.500000  -6.500000  -7.000000
50%     0.000000  -5.000000  -3.000000
75%     4.000000   3.000000   2.000000
max     6.000000   9.000000   9.000000

In [17]:
df.index

RangeIndex(start=0, stop=15, step=1)

In [18]:
list(df.index)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [19]:
df.columns

Index(['x1', 'x2', 'x3'], dtype='object')

In [20]:
df.shape

(15, 3)

In [21]:
df.to_numpy()

array([[  0,  -7,   6],
       [ -4,  -4,  -7],
       [ -8,  -9,   2],
       [ -6,   0,   1],
       [ -9,  -5,  -8],
       [ -8,   9,  -1],
       [ -5,  -6, -10],
       [  5,   8,   7],
       [  6,  -5,  -3],
       [  1,  -9,  -5],
       [  5,   9,  -9],
       [  4,  -8,  -7],
       [  4,  -5,   2],
       [  0,   6,  -3],
       [  2,  -1,   9]])

In [22]:
df.T

0  1  2  3  4  5   6  7  8  9  10  11  12  13  14
x1  0 -4 -8 -6 -9 -8  -5  5  6  1   5   4   4   0   2
x2 -7 -4 -9  0 -5  9  -6  8 -5 -9   9  -8  -5   6  -1
x3  6 -7  2  1 -8 -1 -10  7 -3 -5  -9  -7   2  -3   9

In [23]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(5, 3)), 
    columns=['x1', 'x2', 'x3']
)

df

x1  x2  x3
0   5   8   1
1   6   0   3
2   8   4   3
3   6   9   0
4   8   7   1

In [24]:
print(df['x1'])
print(type(df['x1']))

0    5
1    6
2    8
3    6
4    8
Name: x1, dtype: int32
<class 'pandas.core.series.Series'>


In [25]:
data = {
    'feature1': np.arange(15),
    'feature2': np.linspace(0, 10, 15),
    'feature3': 'string',
}
df = pd.DataFrame(data, index=list('ABCDEFGHIJKLMNO'))
df.head()

feature1  feature2 feature3
A         0  0.000000   string
B         1  0.714286   string
C         2  1.428571   string
D         3  2.142857   string
E         4  2.857143   string

In [26]:
df.iloc[2]

feature1          2
feature2    1.42857
feature3     string
Name: C, dtype: object

In [27]:
df.loc['C']

feature1          2
feature2    1.42857
feature3     string
Name: C, dtype: object

In [28]:
df.iloc[2, 1]

1.4285714285714286

In [29]:
df.loc['C', 'feature2']

1.4285714285714286

# Задание
Выведите часть фрейма со второго ряда по девятый (индексы с 'C' по 'I') и только feature1 и feature3:

In [31]:
data = {
    'feature1': np.arange(15),
    'feature2': np.linspace(0, 10, 15),
    'feature3': 'string',
}
df = pd.DataFrame(data, index=list('ABCDEFGHIJKLMNO'))
df.head()

feature1  feature2 feature3
A         0  0.000000   string
B         1  0.714286   string
C         2  1.428571   string
D         3  2.142857   string
E         4  2.857143   string

In [32]:
df.loc['C':'I',['feature1','feature3']]

feature1 feature3
C         2   string
D         3   string
E         4   string
F         5   string
G         6   string
H         7   string
I         8   string

In [33]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   1   6   8
1   8   4   3
2   1   9   0

In [34]:
df['x1'] > 5

0     False
1      True
2     False
3      True
4     False
5     False
6      True
7     False
8     False
9      True
10    False
11    False
12    False
13     True
14     True
Name: x1, dtype: bool

In [35]:
mask = df['x1'] > 5
df[mask]

# Или df[df['x1'] > 5]

x1  x2  x3
1    8   4   3
3    7   6   2
6    7   9   5
9    8   1   1
13   7   7   0
14   6   1   5

In [36]:
df[~(df['x1'] > 5)]

x1  x2  x3
0    1   6   8
2    1   9   0
4    4   9   7
5    2   8   1
7    0   4   1
8    1   8   1
10   4   1   9
11   1   2   1
12   4   5   7

# Задание
Выберите записи во фрейме, которые по признаку x1 имеют значение больше 3, а по признаку x3 - меньше 8.

In [37]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   3   9   3
1   1   7   7
2   0   6   6

In [38]:
df[df['x1'] >3]
df[df['x3'] <8]


x1  x2  x3
0    3   9   3
1    1   7   7
2    0   6   6
4    5   0   7
5    9   7   6
6    9   4   6
7    8   5   6
8    3   6   1
9    8   3   7
10   8   3   1
13   6   7   3
14   8   9   3

In [41]:
import pandas as pd
import numpyas np
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)

df[df['x1'] >3]
df[df['x3'] <8]
df.loc[:,['x1','x2']]


x1  x2
0    2   1
1    6   1
2    7   0
3    9   5
4    5   6
5    4   0
6    9   8
7    3   8
8    2   8
9    1   6
10   0   4
11   0   2
12   5   3
13   5   0
14   1   0

# Операции с рядами / Новые колонки
Работа с фреймами и рядами данных в pandas поддерживает многие операции по аналогии с работой в numpy.

In [42]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   1   7   2
1   5   2   9
2   6   7   1

In [43]:
# Создать новую колонку можно по аналогии с новым ключем в словаре
# Сложение нескольких Series и запись в новую колонку
df['x1+x2'] = df['x1'] + df['x2']
df.head(3)

x1  x2  x3  x1+x2
0   1   7   2      8
1   5   2   9      7
2   6   7   1     13

In [44]:
# Поэлементное умножение
df['x1*x3'] = df['x1'] * df['x3']
df.head(3)

x1  x2  x3  x1+x2  x1*x3
0   1   7   2      8      2
1   5   2   9      7     45
2   6   7   1     13      6

In [45]:

# Взятие среднего по колонке (метод Series.mean())
df['x1'].mean()

4.2

In [46]:

# Использование функций numpy для работы с колонками
df['x2_exp'] = np.exp(df['x2'])
df.head(3)

x1  x2  x3  x1+x2  x1*x3       x2_exp
0   1   7   2      8      2  1096.633158
1   5   2   9      7     45     7.389056
2   6   7   1     13      6  1096.633158

In [47]:

df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(3, 3)), 
    columns=['x1', 'x2', 'x3']
)
df

x1  x2  x3
0   1   5   2
1   9   9   0
2   5   3   5

In [48]:

# Обязательно требование к функции - один аргумент
# Эта функция будет передана в apply() и pandas
#   будет вызывать ее и передавать в нее 
#   по одному элементу из ряда
# Возвращать функция должна результат операции над элементом
def my_func(x):
    print(type(x))
    print(x)
    return x*2

df['result'] = df['x1'].apply(my_func)
df

<class 'int'>
1
<class 'int'>
9
<class 'int'>
5


x1  x2  x3  result
0   1   5   2       2
1   9   9   0      18
2   5   3   5      10

# Операции с фреймами
Переименование колонок / индексов

In [49]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   7   9   5
1   9   8   2
2   0   8   7

In [50]:
# Методу передается в аргумент columns словарь, 
#   в котором ключи - имена колонок,
#   значения - новые имена для переименования
df.rename(
    columns={
        'x1': 'new_name_for_x1',
        'x3': 'that_not_x3' 
    },
    inplace=True
)
df.head(3)

new_name_for_x1  x2  that_not_x3
0                7   9            5
1                9   8            2
2                0   8            7

# Задание
Переименуйте индексы и колонки во фрейме

In [51]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(5, 3)), 
    index=['A', 'B', 'C', 'D', 'E'], 
    columns=['x1', 'x2', 'x3']
)
df

x1  x2  x3
A   2   4   0
B   0   3   1
C   4   6   9
D   7   2   3
E   3   0   8

# TODO - переименуйте индексы [A, C] -> [indA, indC] 
#           и колонки [x1, x3] -> [new1, new3]

In [54]:

df = pd.DataFrame(
    [[1, 2, 6], [5, 1, 1], [8, 4, 6], [4, 1, 1], [9, 9, 0], [-1, 2, 1], [5, 5, 5]],
    columns = ['x1', 'x2', 'x3']
)
df
df.query('x1>x3')


x1  x2  x3
1   5   1   1
2   8   4   6
3   4   1   1
4   9   9   0

In [55]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   4   5   5
1   7   8   5
2   0   9   8

In [56]:
df.drop(columns=['x2'], inplace=True)
df.head(3)

x1  x3
0   4   5
1   7   5
2   0   8

# Определение количества NaN

In [57]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(5, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.iloc[0, :2] = np.nan
df.iloc[2, 1:] = np.nan

df

x1   x2   x3
0  NaN  NaN  3.0
1  7.0  1.0  0.0
2  2.0  NaN  NaN
3  8.0  1.0  0.0
4  4.0  8.0  5.0

In [58]:
df.isna()

x1     x2     x3
0   True   True  False
1  False  False  False
2  False   True   True
3  False  False  False
4  False  False  False

In [59]:

df.isna().sum()

x1    1
x2    2
x3    1
dtype: int64

In [60]:
df


x1   x2   x3
0  NaN  NaN  3.0
1  7.0  1.0  0.0
2  2.0  NaN  NaN
3  8.0  1.0  0.0
4  4.0  8.0  5.0

In [61]:
df['x2'].fillna(3, inplace=True)
df

x1   x2   x3
0  NaN  3.0  3.0
1  7.0  1.0  0.0
2  2.0  3.0  NaN
3  8.0  1.0  0.0
4  4.0  8.0  5.0

# Информация об уникальных значениях

In [62]:
df = pd.DataFrame({
    'col1': ['high', 'high', 'low', 'med', 'low', 'low', 'med', 'low', 'low', 'high'],
    'col2': [0, 1, 1, 2, 3, 1, 1, 2, 2, 2]
})
df

col1  col2
0  high     0
1  high     1
2   low     1
3   med     2
4   low     3
5   low     1
6   med     1
7   low     2
8   low     2
9  high     2

In [63]:
# Метод DataFrame.nunique() позволяет вывести 
#   количество уникальных значений в каждой колонке
# Результат - Series с индексами - названиями колонок
df.nunique()

col1    3
col2    4
dtype: int64

In [64]:
# Метод Series.value_counts() показывает уникальные значения в ряду
#   и указывает их количество
df['col1'].value_counts()

low     5
high    3
med     2
Name: col1, dtype: int64

In [65]:
# Результат - Series с индексами - уникальными значениями
df['col2'].value_counts()


2    4
1    4
3    1
0    1
Name: col2, dtype: int64

# Фильтрация

In [66]:
df = pd.DataFrame(np.array(([1, 2, 3], [4, 5, 6])),
                  index=['mouse', 'rabbit'],
                  columns=['col_one', 'col_two', 'col_three'])
df

col_one  col_two  col_three
mouse         1        2          3
rabbit        4        5          6

In [67]:
# Отфильтровать по именам колонок
# Аналогично df[['col_one', 'col_three']]
df.filter(items=['col_one', 'col_three'], axis='columns')


col_one  col_three
mouse         1          3
rabbit        4          6

In [68]:
# Отфильтровать по регулярному выражению
# Оставить только те колонки, которые оканчиваются на букву "o"
df.filter(regex='o$', axis='columns')

col_two
mouse         2
rabbit        5

# Задание
Отфильруйте записи по строке, содержащейся в имени индекса (аргумент like):

In [69]:
df = pd.DataFrame(np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9])),
                  index=['dog in house', 'cat in house', 'pig in farm'],
                  columns=['x1', 'x2', 'x3'])
df

x1  x2  x3
dog in house   1   2   3
cat in house   4   5   6
pig in farm    7   8   9

In [70]:
df.filter(like='house',axis='index')

x1  x2  x3
dog in house   1   2   3
cat in house   4   5   6

In [71]:
df = pd.DataFrame({
    'col1': ['A', 'A', 'B', np.nan, 'D', 'C'],
    'col2': [2, 1, 9, 8, 7, 4],
    'col3': [0, 1, 9, 4, 2, 3],
    'col4': ['a', 'B', 'c', 'D', 'e', 'F']
}, index=['A', 'B', 'C', 'D', 'E', 'F'])
df

col1  col2  col3 col4
A    A     2     0    a
B    A     1     1    B
C    B     9     9    c
D  NaN     8     4    D
E    D     7     2    e
F    C     4     3    F

In [72]:
df.sort_values(by='col2', axis='rows')

col1  col2  col3 col4
B    A     1     1    B
A    A     2     0    a
F    C     4     3    F
E    D     7     2    e
D  NaN     8     4    D
C    B     9     9    c

# Задание
Отсортируйте данные:

In [73]:
df = pd.DataFrame(
    np.random.randint(0, 20, size=(5, 5)), 
    columns=['col1', 'col2', 'col3', 'col4', 'col5']
)
df

col1  col2  col3  col4  col5
0    13     9    12    14     4
1     2    13     6    12    10
2     7    16     6     6     6
3     9     7     5    13     4
4     3     7    14     9     4

In [74]:
df = pd.DataFrame({
    'temp': [59, 22, -10, 38, 20, 40, 38, 47, 20, 15, 13, 44, 57, 32, 38]
})
df.head()

temp
0    59
1    22
2   -10
3    38
4    20

In [75]:
df['temp_cat'] = pd.cut(
    x=df['temp'],
    bins=[-10, 10, 25, 60],
    labels=['low', 'medium', 'high'],
    # Флаг, чтобы самое левое значение границы входило в первый диапазон
    include_lowest=True
)
df.head()

temp temp_cat
0    59     high
1    22   medium
2   -10      low
3    38     high
4    20   medium

In [76]:
df['temp_cat'].dtype

CategoricalDtype(categories=['low', 'medium', 'high'], ordered=True)

In [77]:
result_after_cut = pd.cut(
    x=df['temp'],
    bins=[-10, 10, 25, 60],
    include_lowest=True
)
# Взглянем на имена
result_after_cut.unique()

[(25.0, 60.0], (10.0, 25.0], (-10.001, 10.0]]
Categories (3, interval[float64]): [(-10.001, 10.0] < (10.0, 25.0] < (25.0, 60.0]]

In [78]:
result_after_cut = pd.cut(
    x=df['temp'],
    bins=3
)

# Задание
Разделите показатель качества в диапазоне $[0, 100]$ на три группы: плохое $[0-20]$, среднее $(20-45]$, хорошее $(45-85]$, отличное $(85-100]$. Выясните, что происходит со значениями, которые не попадают в диапазоны категорий:

In [79]:
df = pd.DataFrame({
    'quality': [ 7, 67, 21, 38,  2, -2, 79, 22,  5, 31, 77, 72, 23, 64, 99]
})
df.head()

quality
0        7
1       67
2       21
3       38
4        2

In [80]:
df['q_cat'] = pd.cut(
    x=df['quality'],
    bins=[0, 20, 45, 85, 100],
    labels=['bad', 'mid', 'good','excellent'],
    include_lowest=True
)
df

quality      q_cat
0         7        bad
1        67       good
2        21        mid
3        38        mid
4         2        bad
5        -2        NaN
6        79       good
7        22        mid
8         5        bad
9        31        mid
10       77       good
11       72       good
12       23        mid
13       64       good
14       99  excellent

# Агрегация данных

In [81]:
df = pd.DataFrame([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [np.nan, np.nan, np.nan]],
                  columns=['A', 'B', 'C'])
df

A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

In [82]:
df.aggregate(['min', 'mean'], axis='rows')

A    B    C
min   1.0  2.0  3.0
mean  4.0  5.0  6.0

In [83]:
df.aggregate({
    'A': ['sum', 'min'],
    'B': ['max', 'min'],
    'C': [np.sum, np.mean],
})

A    B     C
max    NaN  8.0   NaN
mean   NaN  NaN   6.0
min    1.0  2.0   NaN
sum   12.0  NaN  18.0

# Задание
Произведите агрегацию средним по рядам

In [84]:
df = pd.DataFrame(
    ([1, 2, 3], [4, 5, 6], [7, 8, 9]), 
    columns=['x1', 'x2', 'x3'])
df

x1  x2  x3
0   1   2   3
1   4   5   6
2   7   8   9

In [85]:
df.aggregate(['mean'], axis='rows')

x1   x2   x3
mean  4.0  5.0  6.0

In [86]:
data = [
    [1, 4.7, 60],
    [3, 4.5, 45],
    [4, 4.8, 40],
    [1, 4.9, 58],
    [2, 4.1, 50],
    [2, 4.2, 49],
    [2, 4.4, 49],
    [3, 4.9, 46],
    [4, 4.3, 33],
]

stud_df = pd.DataFrame(data, columns=['Grade', 'Test_Mark', 'Time'])
stud_df

Grade  Test_Mark  Time
0      1        4.7    60
1      3        4.5    45
2      4        4.8    40
3      1        4.9    58
4      2        4.1    50
5      2        4.2    49
6      2        4.4    49
7      3        4.9    46
8      4        4.3    33

In [88]:
gr_stud_df = stud_df.groupby(by='Grade')

In [89]:
print(type(gr_stud_df))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>


In [90]:
gr_stud_df.groups

{1: Int64Index([0, 3], dtype='int64'),
 2: Int64Index([4, 5, 6], dtype='int64'),
 3: Int64Index([1, 7], dtype='int64'),
 4: Int64Index([2, 8], dtype='int64')}

In [91]:
gr_stud_df.agg('mean')

Test_Mark       Time
Grade                      
1       4.800000  59.000000
2       4.233333  49.333333
3       4.700000  45.500000
4       4.550000  36.500000

In [92]:
gr_stud_df.agg(['mean', 'min'])

Test_Mark            Time    
           mean  min       mean min
Grade                              
1      4.800000  4.7  59.000000  58
2      4.233333  4.1  49.333333  49
3      4.700000  4.5  45.500000  45
4      4.550000  4.3  36.500000  33

In [93]:
res = gr_stud_df.agg({
    'Test_Mark': ['mean', 'min'],
    'Time': ['min']
})

print(type(res))
res

<class 'pandas.core.frame.DataFrame'>


Test_Mark      Time
           mean  min  min
Grade                    
1      4.800000  4.7   58
2      4.233333  4.1   49
3      4.700000  4.5   45
4      4.550000  4.3   33

In [94]:
res['Test_Mark']['mean']

Grade
1    4.800000
2    4.233333
3    4.700000
4    4.550000
Name: mean, dtype: float64

# Задание
Сгруппируйте данные по признаку x2 и найдите медиану и максимальное значения по признакам x1, x3:

In [96]:
df = pd.DataFrame({
    'x1': np.random.randint(10, 100, size=(200, )),
    'x2': np.random.choice(['low', 'high', 'medium'], size=(200, )),
    'x3': np.random.randint(-20, 30, size=(200, )),
})
df.head()

x1      x2  x3
0  22     low  17
1  18    high   6
2  21     low  21
3  83    high  -4
4  67  medium  23

In [97]:
group_df=df.groupby(by='x2')
res = group_df.agg({
    'x1': ['mean', 'max'],
    'x3': ['mean', 'max']
})

print(type(res))
res

<class 'pandas.core.frame.DataFrame'>


x1            x3    
             mean max      mean max
x2                                 
high    56.800000  98  4.506667  29
low     51.781250  97  4.546875  29
medium  55.065574  98  3.770492  29

# Сохранение / загрузка данных (работа с CSV)

In [99]:
import string

df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3'],
    index=list(string.ascii_uppercase)[:15]
)
df.head(3)

x1  x2  x3
A   2   2   9
B   4   8   6
C   8   7   1

In [100]:
df.to_csv('my_first_file.csv')

In [101]:
df = pd.read_csv('my_first_file.csv')
df.head(3)

Unnamed: 0  x1  x2  x3
0          A   2   2   9
1          B   4   8   6
2          C   8   7   1

In [102]:
df = pd.read_csv('my_first_file.csv', index_col=0)
df.head(3)

x1  x2  x3
A   2   2   9
B   4   8   6
C   8   7   1

# Задание
Разберитесь в аргументах DataFrame.to_csv() и сохраните данные в файл так, чтобы в файл индекс не сохранялся.

In [103]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3'],
    index=list(string.ascii_uppercase)[:15]
)
df.head(3)



x1  x2  x3
A   6   2   1
B   5   7   9
C   7   6   8

In [104]:
df.to_csv('my_second_fail.csv',index=False)
df = pd.read_csv('my_second_fail.csv')
df.head(3)

x1  x2  x3
0   6   2   1
1   5   7   9
2   7   6   8

# Задачки

In [106]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'name':'YIN',
'year': '10',
'age': np.array([35] * 1, dtype='int32'),
'colcr': pd.Categorical(["red"])

                   })
df


name year  age colcr
0  YIN   10   35   red

In [107]:
ds1 = pd.Series([1, 2, 3, 4, 5])
ds2 = pd.Series([4, 5, 6, 7, 8, 1, 9])
mask=ds1.isin(ds2)
print(ds1[~mask])

1    2
2    3
dtype: int64


In [108]:
import pandas as pd
ds = pd.Series([2, 2, 2, 4, 4, 4, 3, 1, 1, 1, 1, 4])
print(ds.replace({2:"other",3:"other"}))


0     other
1     other
2     other
3         4
4         4
5         4
6     other
7         1
8         1
9         1
10        1
11        4
dtype: object


In [109]:
import pandas as pd
ds = pd.Series(['how', 'to', 'use', 'pandas?'])

ds = ds.apply(str.title)
print(ds)


0        How
1         To
2        Use
3    Pandas?
dtype: object


In [111]:
import pandas as pd
import numpy as np
df = pd.DataFrame(
np.random.randint(0, 4, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df
df['x1'].max()


3

In [114]:
import pandas as pd
import numpy as np
df = pd.read_csv('https://raw.githubusercontent.com/Kail4eK/ml_edu/master/datasets/Cars93_miss.csv')
na=df.isnull()
print(na)


    Manufacturer  Model   Type  Min.Price  Price  Max.Price  MPG.city  \
0          False  False  False      False  False      False     False   
1           True  False  False      False  False      False     False   
2          False  False  False      False  False      False     False   
3          False  False  False       True  False      False     False   
4          False  False  False       True  False       True     False   
..           ...    ...    ...        ...    ...        ...       ...   
88         False  False  False      False  False      False     False   
89         False  False  False      False  False      False     False   
90         False  False  False      False  False      False     False   
91         False  False  False      False  False      False     False   
92          True  False  False      False  False      False     False   

    MPG.highway  AirBags  DriveTrain  ...  Passengers  Length  Wheelbase  \
0         False    False       False  ...      

In [115]:
df = pd.read_csv('https://raw.githubusercontent.com/Kail4eK/ml_edu/master/datasets/Cars93_miss.csv')
na=df.isnull()
print(na[['Min.Price']].any(axis=1))
df1=df.fillna("mean")
print(df1)


0     False
1     False
2     False
3      True
4      True
      ...  
88    False
89    False
90    False
91    False
92    False
Length: 93, dtype: bool
   Manufacturer    Model     Type Min.Price Price Max.Price MPG.city  \
0         Acura  Integra    Small      12.9  15.9      18.8       25   
1          mean   Legend  Midsize      29.2  33.9      38.7       18   
2          Audi       90  Compact      25.9  29.1      32.3       20   
3          Audi      100  Midsize      mean  37.7      44.6       19   
4           BMW     535i  Midsize      mean    30      mean       22   
..          ...      ...      ...       ...   ...       ...      ...   
88   Volkswagen  Eurovan      Van      16.6  19.7      22.7       17   
89   Volkswagen   Passat  Compact      17.6    20      22.4       21   
90   Volkswagen  Corrado   Sporty      22.9  23.3      23.7       18   
91        Volvo      240  Compact      21.8  22.7      23.5       21   
92         mean      850  Midsize      24.8  26.7   

In [116]:
df = pd.DataFrame(np.random.randint(0, 10, size=(5, 6)), columns=list('fbecda'))
df.reindex(sorted(df.columns),axis=1)

a  b  c  d  e  f
0  2  7  7  7  4  7
1  6  1  5  3  2  0
2  3  1  3  2  5  8
3  1  3  8  4  6  1
4  5  6  8  9  2  1

In [118]:
import pandas as pd
import numpy as np
df = pd.read_csv('https://raw.githubusercontent.com/Kail4eK/ml_edu/master/datasets/Cars93_miss.csv')
df
df.loc[[20,40,60,80],['Manufacturer','Model','Type']]


Manufacturer    Model     Type
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

In [122]:

ds = pd.Series(['how', 'to', 'use', 'pandas?'])
ds= ds.str.len() 
ds


0    3
1    2
2    3
3    7
dtype: int64